project:
  type: website
  output-dir: slides
  resources:
    - images/


author:
    - name: "Ruben Rodríguez"
      email: "ruben.rodriguez@urjc.es"
      affiliation: "URJC"
    - name: "Natalia Madrueño"
      email: "natalia.madrueno@urjc.es"
      affiliation: "URJC"
date: 09/09/2025

format:
  revealjs:
    theme: [default, dslab-theme.scss]
    auto-stretch: true
    width: 1280
    height: 720
    center: false
    slide-number: true
    scrollable: false
    max-scale: 1.0
    min-scale: 0.5
    disableLayout: false
    logo: images/DSLab_logo_2.png
    pdf-max-pages-per-slide: 1
    pdf-separate-fragments: false
    progress: true
    menu:
      openButton: true
      openSlideNumber: false
      openOnInit: false
      keyboard: false
      markers: false
      titleSelector: ""
      side: left
      width: third
    lang: es
    html-math-method: katex
    chalkboard:
      buttons: true
    preview-links: auto
    show-notes: false
    toc: true
    toc-depth: 1
    template-partials:
      - title-slide.html
    include-after-body: mermaid-fix.html

execute:
  freeze: true

bibliography: references.bib


