project:
  type: website
  output-dir: slides

format:
  revealjs:
    theme: [default]
    auto-stretch: true
    width: 1280
    height: 720
    center: false
    slide-number: true
    scrollable: false
    max-scale: 0.9
    min-scale: 0.5
    # filters:
    #   - metropolis-beamer/metropolis-header.lua
    #   - metropolis-beamer/custom-block.lua
    # lang: es
    # # theme: [default, theme.scss]
    # html-math-method: katex
    # chalkboard:
    #   buttons: true
    # preview-links: auto
    # show-notes: false
    # pdf-max-pages-per-slide: 1
    # progress: true
    # menu:
    #   openButton: true
    #   openSlideNumber: false
    #   openOnInit: false
    #   keyboard: false
    #   markers: false
    #   titleSelector: ""
    #   side: left
    #   width: third
    # toc: true
    # toc-depth: 1
    # logo: theme_images/URJClogo.png
    # title-slide-attributes:
    #   data-background-image: theme_images/background_fronpage.png
    #   data-background-size: 33%
    #   data-background-position: center 70%
    # include-after-body: mermaid-fix.html

  beamer: 
    template: dslab.beamer.tex
    keep-tex: true
    include-in-header:
      text: |
        \providecommand{\pandocbounded}[1]{#1}

execute:
  freeze: true

bibliography: references.bib


